# Konfiguracja MySQL (Zmień to na poprawne dane aby plugin działał)
mysql-host: "localhost"
mysql-port: "3306"
mysql-user: "root"
mysql-pass: ""
mysql-dbname: "mcjk_mc_stats"

web-stats-root: "https://maciejka.xyz/mc-1p1t/stats/" # Podstawa adresu URL wysyłanego do graczy gdy np. poproszą o ranking graczy lub własne statystyki